backend:
  name: git-gateway
media_folder: static/img
public_folder: /img
collections:
  - name: 'blog'
    label: 'Blog'
    folder: 'content/blog'
    create: true
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    editor:
      preview: false
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Publish Date', name: 'date', widget: 'datetime' }
      - { label: 'Description', name: 'description', widget: 'string' }
      - { label: 'Body', name: 'body', widget: 'markdown' }
  - label: "Pages"
    name: "pages"
    files:
      - label: "Home Page"
        name: "home"
        file: "content/_index.md"
        editor:
          preview: false
        fields:
          - {label: 'Title', name: 'title', widget: 'string'}
          - {label: 'Sub Title', name: 'sub_title', widget: 'string'}
          - {label: 'Dunedin Parking logo', name: 'dun_park_logo', widget: 'image'}
          - {label: 'Intro', name: 'intro', widget: 'markdown'}
          - {label: 'Photo', name: 'photo', hint: 'The hero image', widget: 'image'}
          - label: Map
            name: map_home
            widget: list
            fields:
              - { label: 'Location Name', name: 'loc_name', widget: 'string' }
              - { label: 'Body', name: 'body', widget: 'markdown' }
              - { label: 'Location link', name: 'loc_link', required: false, widget: 'string' }
              - { label: 'Location image', name: 'loc_img', required: false, widget: 'image' }
          - label: Testimonials
            name: testimonials
            widget: list
            fields:
              - { label: 'Body', name: 'body', required: false, widget: 'markdown' }
          - label: Footer
            name: footer
            widget: list
            fields:
              - { label: 'Body', name: 'body', required: false, widget: 'markdown' }
